//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainersSchoolingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int FeeId { get; set; }
        public string FeeType { get; set; }
        public string Amount { get; set; }
        public string Description { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> Class { get; set; }
    
        public virtual Class Class1 { get; set; }
        public virtual TrainerUser TrainerUser { get; set; }
        public virtual TrainerUser TrainerUser1 { get; set; }
    }
}
